# Generated by Django 3.0.5 on 2020-06-30 16:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import frutonp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Comment')),
                ('editted', models.BooleanField(default=False)),
                ('commented_at', models.DateTimeField(auto_now=True)),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField(verbose_name='Description')),
                ('foodType', models.CharField(choices=[('FAP', 'Apple'), ('FBA', 'Banana'), ('FLI', 'Litchi'), ('FMA', 'Mango'), ('FOR', 'Orange'), ('VBG', 'Bitter Gourd'), ('VCA', 'Cabbage'), ('VCF', 'Cauliflower'), ('VLF', 'Ladies Finger'), ('VPK', 'Pumpkin')], max_length=30, verbose_name='Food Type')),
                ('price', models.BigIntegerField()),
                ('quantity', models.CharField(choices=[('kg', 'kg'), ('250gm', '250gm'), ('200gm', '200gm'), ('500gm', '500gm'), ('2kg', '2kg'), ('5kg', '5kg'), ('10kg', '10kg'), ('25kg', '25kg'), ('50kg', '50kg'), ('quintal', 'quintal')], max_length=30)),
                ('expire', models.CharField(choices=[('1', '1 day'), ('2', '2 days'), ('3', '3 days'), ('4', '4 days'), ('5', '5 days'), ('6', '6 days'), ('7', '7 days'), ('8', '8 days'), ('9', '9 days'), ('10', '10 days'), ('10', '10 days'), ('11', '11 days'), ('12', '12 days'), ('13', '13 days'), ('14', '14 days'), ('15', '15 days')], default='10', max_length=10, null=True)),
                ('phone2', models.CharField(max_length=10, null=True)),
                ('location', models.CharField(max_length=150, null=True)),
                ('thumbnail', models.CharField(max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True, verbose_name='Uploaded At')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Reply')),
                ('replied_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='posts.Comment')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='post/', validators=[frutonp.utils.file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Photos')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.Post'),
        ),
    ]
