# Generated by Django 3.0.5 on 2020-09-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200709_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='expire',
        ),
    ]
