# Generated by Django 3.0.3 on 2020-04-18 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import frutonp.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=48)),
                ('phone1', models.BigIntegerField()),
                ('token', models.CharField(max_length=65, null=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('signed_up', models.DateTimeField(null=True, verbose_name='Signed_Up')),
                ('name_updated', models.DateTimeField(null=True, verbose_name='Name updated')),
                ('phone_updated', models.DateTimeField(null=True, verbose_name='Phone updated')),
                ('password_updated', models.DateTimeField(null=True, verbose_name='Password updated')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MyUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=255, null=True)),
                ('desc', models.TextField(default='', null=True)),
                ('phone2', models.CharField(default='', max_length=10, null=True)),
                ('pp', models.ImageField(default='pp/no_pp.png', null=True, upload_to='pp/', validators=[frutonp.utils.file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('modified_at', models.DateTimeField()),
                ('myuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
