# Generated by Django 3.0.5 on 2020-09-10 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_auto_20200910_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='token',
        ),
    ]
