# Generated by Django 3.0.5 on 2020-08-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notif',
            old_name='seen',
            new_name='is_seen',
        ),
    ]
